package com.entity;
// Generated Apr 6, 2019 4:41:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * ItemCategory generated by hbm2java
 */
public class ItemCategory  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set itemProfiles = new HashSet(0);

    public ItemCategory() {
    }

    public ItemCategory(String name, Set itemProfiles) {
       this.name = name;
       this.itemProfiles = itemProfiles;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getItemProfiles() {
        return this.itemProfiles;
    }
    
    public void setItemProfiles(Set itemProfiles) {
        this.itemProfiles = itemProfiles;
    }




}


