package com.entity;
// Generated Apr 6, 2019 4:41:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * ItemProfile generated by hbm2java
 */
public class ItemProfile  implements java.io.Serializable {


     private Integer id;
     private ItemCategory itemCategory;
     private String generatedId;
     private String itemName;
     private String imageUrl;
     private Double price;
     private Date createDateTime;
     private Date updateDateTime;
     private Boolean isActive;
     private Set userCartItems = new HashSet(0);

    public ItemProfile() {
    }

	
    public ItemProfile(ItemCategory itemCategory) {
        this.itemCategory = itemCategory;
    }
    public ItemProfile(ItemCategory itemCategory, String generatedId, String itemName, String imageUrl, Double price, Date createDateTime, Date updateDateTime, Boolean isActive, Set userCartItems) {
       this.itemCategory = itemCategory;
       this.generatedId = generatedId;
       this.itemName = itemName;
       this.imageUrl = imageUrl;
       this.price = price;
       this.createDateTime = createDateTime;
       this.updateDateTime = updateDateTime;
       this.isActive = isActive;
       this.userCartItems = userCartItems;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public ItemCategory getItemCategory() {
        return this.itemCategory;
    }
    
    public void setItemCategory(ItemCategory itemCategory) {
        this.itemCategory = itemCategory;
    }
    public String getGeneratedId() {
        return this.generatedId;
    }
    
    public void setGeneratedId(String generatedId) {
        this.generatedId = generatedId;
    }
    public String getItemName() {
        return this.itemName;
    }
    
    public void setItemName(String itemName) {
        this.itemName = itemName;
    }
    public String getImageUrl() {
        return this.imageUrl;
    }
    
    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }
    public Double getPrice() {
        return this.price;
    }
    
    public void setPrice(Double price) {
        this.price = price;
    }
    public Date getCreateDateTime() {
        return this.createDateTime;
    }
    
    public void setCreateDateTime(Date createDateTime) {
        this.createDateTime = createDateTime;
    }
    public Date getUpdateDateTime() {
        return this.updateDateTime;
    }
    
    public void setUpdateDateTime(Date updateDateTime) {
        this.updateDateTime = updateDateTime;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public Set getUserCartItems() {
        return this.userCartItems;
    }
    
    public void setUserCartItems(Set userCartItems) {
        this.userCartItems = userCartItems;
    }




}


