package com.entity;
// Generated Apr 6, 2019 4:41:29 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * PasswordRecovery generated by hbm2java
 */
public class PasswordRecovery  implements java.io.Serializable {


     private Integer id;
     private UserLogin userLogin;
     private String authCode;
     private Date createDateTime;
     private Date useDateTime;
     private Boolean isActive;

    public PasswordRecovery() {
    }

	
    public PasswordRecovery(UserLogin userLogin) {
        this.userLogin = userLogin;
    }
    public PasswordRecovery(UserLogin userLogin, String authCode, Date createDateTime, Date useDateTime, Boolean isActive) {
       this.userLogin = userLogin;
       this.authCode = authCode;
       this.createDateTime = createDateTime;
       this.useDateTime = useDateTime;
       this.isActive = isActive;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public UserLogin getUserLogin() {
        return this.userLogin;
    }
    
    public void setUserLogin(UserLogin userLogin) {
        this.userLogin = userLogin;
    }
    public String getAuthCode() {
        return this.authCode;
    }
    
    public void setAuthCode(String authCode) {
        this.authCode = authCode;
    }
    public Date getCreateDateTime() {
        return this.createDateTime;
    }
    
    public void setCreateDateTime(Date createDateTime) {
        this.createDateTime = createDateTime;
    }
    public Date getUseDateTime() {
        return this.useDateTime;
    }
    
    public void setUseDateTime(Date useDateTime) {
        this.useDateTime = useDateTime;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }




}


