package com.entity;
// Generated Apr 6, 2019 4:41:29 PM by Hibernate Tools 4.3.1



/**
 * UserCartItem generated by hbm2java
 */
public class UserCartItem  implements java.io.Serializable {


     private Integer id;
     private ItemProfile itemProfile;
     private UserCart userCart;
     private Integer qty;
     private Double amount;
     private Boolean isActive;

    public UserCartItem() {
    }

	
    public UserCartItem(ItemProfile itemProfile, UserCart userCart) {
        this.itemProfile = itemProfile;
        this.userCart = userCart;
    }
    public UserCartItem(ItemProfile itemProfile, UserCart userCart, Integer qty, Double amount, Boolean isActive) {
       this.itemProfile = itemProfile;
       this.userCart = userCart;
       this.qty = qty;
       this.amount = amount;
       this.isActive = isActive;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public ItemProfile getItemProfile() {
        return this.itemProfile;
    }
    
    public void setItemProfile(ItemProfile itemProfile) {
        this.itemProfile = itemProfile;
    }
    public UserCart getUserCart() {
        return this.userCart;
    }
    
    public void setUserCart(UserCart userCart) {
        this.userCart = userCart;
    }
    public Integer getQty() {
        return this.qty;
    }
    
    public void setQty(Integer qty) {
        this.qty = qty;
    }
    public Double getAmount() {
        return this.amount;
    }
    
    public void setAmount(Double amount) {
        this.amount = amount;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }




}


