package com.entity;
// Generated Apr 6, 2019 4:41:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserCart generated by hbm2java
 */
public class UserCart  implements java.io.Serializable {


     private Integer id;
     private UserProfile userProfile;
     private String generatedId;
     private Date createDateTime;
     private Date updateDateTime;
     private Integer totalQty;
     private Double totalAmount;
     private Date checkOutDateTime;
     private Boolean isActive;
     private Boolean isCheckOut;
     private Set userCartItems = new HashSet(0);

    public UserCart() {
    }

	
    public UserCart(UserProfile userProfile) {
        this.userProfile = userProfile;
    }
    public UserCart(UserProfile userProfile, String generatedId, Date createDateTime, Date updateDateTime, Integer totalQty, Double totalAmount, Date checkOutDateTime, Boolean isActive, Boolean isCheckOut, Set userCartItems) {
       this.userProfile = userProfile;
       this.generatedId = generatedId;
       this.createDateTime = createDateTime;
       this.updateDateTime = updateDateTime;
       this.totalQty = totalQty;
       this.totalAmount = totalAmount;
       this.checkOutDateTime = checkOutDateTime;
       this.isActive = isActive;
       this.isCheckOut = isCheckOut;
       this.userCartItems = userCartItems;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public UserProfile getUserProfile() {
        return this.userProfile;
    }
    
    public void setUserProfile(UserProfile userProfile) {
        this.userProfile = userProfile;
    }
    public String getGeneratedId() {
        return this.generatedId;
    }
    
    public void setGeneratedId(String generatedId) {
        this.generatedId = generatedId;
    }
    public Date getCreateDateTime() {
        return this.createDateTime;
    }
    
    public void setCreateDateTime(Date createDateTime) {
        this.createDateTime = createDateTime;
    }
    public Date getUpdateDateTime() {
        return this.updateDateTime;
    }
    
    public void setUpdateDateTime(Date updateDateTime) {
        this.updateDateTime = updateDateTime;
    }
    public Integer getTotalQty() {
        return this.totalQty;
    }
    
    public void setTotalQty(Integer totalQty) {
        this.totalQty = totalQty;
    }
    public Double getTotalAmount() {
        return this.totalAmount;
    }
    
    public void setTotalAmount(Double totalAmount) {
        this.totalAmount = totalAmount;
    }
    public Date getCheckOutDateTime() {
        return this.checkOutDateTime;
    }
    
    public void setCheckOutDateTime(Date checkOutDateTime) {
        this.checkOutDateTime = checkOutDateTime;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public Boolean getIsCheckOut() {
        return this.isCheckOut;
    }
    
    public void setIsCheckOut(Boolean isCheckOut) {
        this.isCheckOut = isCheckOut;
    }
    public Set getUserCartItems() {
        return this.userCartItems;
    }
    
    public void setUserCartItems(Set userCartItems) {
        this.userCartItems = userCartItems;
    }




}


