package com.entity;
// Generated Apr 6, 2019 4:41:29 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * UserProfile generated by hbm2java
 */
public class UserProfile  implements java.io.Serializable {


     private Integer id;
     private String firstName;
     private String lastName;
     private String phoneNumber;
     private String emailAddress;
     private Date createDateTime;
     private Date updateDateTime;
     private Boolean isActive;
     private Set userLogins = new HashSet(0);
     private Set userCarts = new HashSet(0);

    public UserProfile() {
    }

    public UserProfile(String firstName, String lastName, String phoneNumber, String emailAddress, Date createDateTime, Date updateDateTime, Boolean isActive, Set userLogins, Set userCarts) {
       this.firstName = firstName;
       this.lastName = lastName;
       this.phoneNumber = phoneNumber;
       this.emailAddress = emailAddress;
       this.createDateTime = createDateTime;
       this.updateDateTime = updateDateTime;
       this.isActive = isActive;
       this.userLogins = userLogins;
       this.userCarts = userCarts;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getFirstName() {
        return this.firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    public String getLastName() {
        return this.lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
    public String getPhoneNumber() {
        return this.phoneNumber;
    }
    
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }
    public String getEmailAddress() {
        return this.emailAddress;
    }
    
    public void setEmailAddress(String emailAddress) {
        this.emailAddress = emailAddress;
    }
    public Date getCreateDateTime() {
        return this.createDateTime;
    }
    
    public void setCreateDateTime(Date createDateTime) {
        this.createDateTime = createDateTime;
    }
    public Date getUpdateDateTime() {
        return this.updateDateTime;
    }
    
    public void setUpdateDateTime(Date updateDateTime) {
        this.updateDateTime = updateDateTime;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public Set getUserLogins() {
        return this.userLogins;
    }
    
    public void setUserLogins(Set userLogins) {
        this.userLogins = userLogins;
    }
    public Set getUserCarts() {
        return this.userCarts;
    }
    
    public void setUserCarts(Set userCarts) {
        this.userCarts = userCarts;
    }




}


