package com.entity;
// Generated Apr 6, 2019 4:41:29 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * UserLogin generated by hbm2java
 */
public class UserLogin  implements java.io.Serializable {


     private Integer id;
     private UserProfile userProfile;
     private String userName;
     private String password;
     private Boolean isActive;
     private Boolean isAdmin;
     private Set passwordRecoveries = new HashSet(0);

    public UserLogin() {
    }

	
    public UserLogin(UserProfile userProfile) {
        this.userProfile = userProfile;
    }
    public UserLogin(UserProfile userProfile, String userName, String password, Boolean isActive, Boolean isAdmin, Set passwordRecoveries) {
       this.userProfile = userProfile;
       this.userName = userName;
       this.password = password;
       this.isActive = isActive;
       this.isAdmin = isAdmin;
       this.passwordRecoveries = passwordRecoveries;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public UserProfile getUserProfile() {
        return this.userProfile;
    }
    
    public void setUserProfile(UserProfile userProfile) {
        this.userProfile = userProfile;
    }
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public Boolean getIsActive() {
        return this.isActive;
    }
    
    public void setIsActive(Boolean isActive) {
        this.isActive = isActive;
    }
    public Boolean getIsAdmin() {
        return this.isAdmin;
    }
    
    public void setIsAdmin(Boolean isAdmin) {
        this.isAdmin = isAdmin;
    }
    public Set getPasswordRecoveries() {
        return this.passwordRecoveries;
    }
    
    public void setPasswordRecoveries(Set passwordRecoveries) {
        this.passwordRecoveries = passwordRecoveries;
    }




}


